import ConnectButton from "@/components/ConnectButton";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Gitpass from "@/components/Gitpass";
import SignIn from "@/components/SignIn";
import Grant from "@/components/Grant";
import { useAccount } from "wagmi";
import { useSession } from "next-auth/react";
import Nav from "@/components/Nav";

export default function Home() {
  const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
    useState(false);
  const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);
  const [score, setScore] = useState<number>(0);

  const { address } = useAccount();

  const { data: session } = useSession();

  const closeAll = () => {
    setIsNetworkSwitchHighlighted(false);
    setIsConnectHighlighted(false);
  };

  //TODO: Fix Grant Role Button CallBack.
  //TODO: Fix UI
  return (
    <>
      <Head>
        <title>Avail Wallet Connect</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="grid min-h-screen items-center">
        <div className="flex items-center flex-col gap-12">
          <h1 className="text-3xl font-bold">Avail Faucet Verification</h1>
          <ConnectButton />
          {/* <Account></Account> */}
          {address && <SignIn></SignIn>}
          {address && session && (
            <Gitpass score={score} setScore={setScore}></Gitpass>
          )}
          {/* <DiscodAcc></DiscodAcc> */}
          {score > 1 && <Grant score={score} setScore={setScore}></Grant>}{" "}
          {/* Conditional rendering based on score */}
        </div>
      </main>
    </>
  );
}
